name: iqbal_literature
description: A comprehensive collection of Dr. Allama Iqbal's literary works.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.6

  # Database and Storage
  sqflite: ^2.3.0
  path: ^1.8.3
 
  path_provider: ^2.1.1

  # Firebase
  firebase_core: ^2.27.0
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.8
  firebase_crashlytics: ^3.4.18
  firebase_performance: ^0.9.3+8

  # UI Components
  flutter_native_splash: ^2.3.8
  device_preview: ^1.1.0
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  flutter_markdown: ^0.6.18+2
  shimmer: ^3.0.0

  # Utils
  package_info_plus: ^5.0.1
  intl: ^0.19.0
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.2

  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  get_it: ^8.0.3
  equatable: ^2.0.7
  firebase_storage: ^11.6.9
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.4.0
  timeline_tile: ^2.0.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.14
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.8
  firebase_core_platform_interface: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/icons/
    - assets/images/illustrations/
    - assets/database/data.db
    - assets/fonts/
    - assets/fonts/JameelNooriNastaleeq.ttf
    - assets/images/notebook_lines.png
  
  fonts:
    - family: JameelNooriNastaleeq
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/icons/splash_icon.png
  color_dark: "#121212"
  image_dark: assets/images/icons/splash_icon_dark.png
  android: true
  ios: true
  web: false
